#ifndef BKE_COMMON_H
#define BKE_COMMON_H

#include <cwchar>
#include <climits>

#ifdef LINUX
#include <stdint.h>
#endif

typedef signed char int8_t;
typedef unsigned char uint8_t;
typedef signed short int16_t;
typedef unsigned short uint16_t;
typedef signed int int32_t;
typedef unsigned int uint32_t;
#ifndef LINUX
typedef signed long long int64_t;
typedef unsigned long long uint64_t;
#endif

typedef unsigned long ulong;
typedef unsigned short ushort;
typedef unsigned char uchar;
typedef int8_t Sint8;
typedef uint8_t Uint8;
typedef int16_t Sint16;
typedef uint16_t Uint16;
typedef int32_t Sint32;
typedef uint32_t Uint32;
typedef int64_t Sint64;
typedef uint64_t Uint64;

#ifdef _MSC_VER
#pragma warning(disable:4065) //no "switch statement contains 'default' but no 'case' labels", generated by Bison.
#pragma warning(disable:4996) //no "unsafe" functions
#endif

#if ULONG_MAX<0xFFFFFFFF
#error "longs on this implementation are too small."
#endif

extern ulong sCpuCount;

extern volatile bool sSkip;
extern volatile bool sSkipAll;
extern volatile bool sCtrlSkip;
extern volatile bool sAutomode;

using namespace std;
/////////////////////config////////////////////////

#endif
